import type { Metadata } from 'next';
import '../globals.css';
import Header from '@/components/Header';
import { SearchProvider } from '@/context/SearchContext/SearchContext';
import ThemeProvider from '@/context/ThemeContext/ThemeProvider';

export const metadata: Metadata = {
  title: 'Search Pokemon',
  description: 'Generated by create next app',
};
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
type LayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};
export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = await params;
  const messages = await getMessages({ locale });
  return (
    <html lang={locale}>
      <body className="dark:bg-zinc-900">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <SearchProvider>
            <ThemeProvider>
              <Header />
              <main>{children}</main>
            </ThemeProvider>
          </SearchProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
